#
# BTstack example 'spp_counter' for ESP32 port
#
# Generated by /home/iltis/esp/workspace/btstack/port/esp32
# On Sat Oct 28 14:18:00 2017

PROJECT_NAME := spp_counter

include $(IDF_PATH)/make/project.mk
