#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := I2Cbus

# Add I2Cbus library path to components
EXTRA_COMPONENT_DIRS := $(abspath ..)

include $(IDF_PATH)/make/project.mk
